import time
import re
import os
import requests
import sys

# CONFIGURATION
# ------------------------------------------------------------------
# OPTION 1: TEXTBELT (1 Free SMS per day)
# Phone number format: +15551234567 (International format)
PHONE_NUMBER = "ENTER_YOUR_PHONE_NUMBER_HERE" 

# OPTION 2: TELEGRAM (Unlimited Free)
TELEGRAM_BOT_TOKEN = "" # Get from @BotFather
TELEGRAM_CHAT_ID = ""   # Get from @userinfobot

# OPTION 3: DISCORD (Unlimited Free)
DISCORD_WEBHOOK_URL = "" 
# ------------------------------------------------------------------

LOG_FILE = os.path.expanduser("~/tunnel.log")

def get_tunnel_url():
    """Reads the tunnel log and extracts the trycloudflare URL."""
    print(f"Checking for log file at: {LOG_FILE}")
    
    # Wait for file to exist
    while not os.path.exists(LOG_FILE):
        time.sleep(2)
    
    print("Log file found. Scanning for URL...")
    
    # Scan for URL
    start_time = time.time()
    url_pattern = re.compile(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com")
    
    while time.time() - start_time < 120: # timeout 2 mins
        try:
            with open(LOG_FILE, "r") as f:
                content = f.read()
                match = url_pattern.search(content)
                if match:
                    return match.group(0)
        except Exception as e:
            print(f"Error reading log: {e}")
            
        time.sleep(2)
        
    return None

def send_sms(url):
    if "ENTER_YOUR" in PHONE_NUMBER:
        return False
        
    print(f"Sending SMS to {PHONE_NUMBER}...")
    try:
        resp = requests.post('https://textbelt.com/text', {
            'phone': PHONE_NUMBER,
            'message': f"ResoFly is Online! Link: {url}",
            'key': 'textbelt', # Free key (1 per day)
        })
        print(f"SMS Result: {resp.json()}")
        return resp.json().get('success')
    except Exception as e:
        print(f"SMS Failed: {e}")
        return False

def send_telegram(url):
    if not TELEGRAM_BOT_TOKEN:
        return False
    print("Sending Telegram...")
    requests.post(
        f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
        json={"chat_id": TELEGRAM_CHAT_ID, "text": f"🚀 ResoFly System Online\n\nAccess here: {url}"}
    )

def send_discord(url):
    if not DISCORD_WEBHOOK_URL:
        return False
    print("Sending Discord...")
    requests.post(
        DISCORD_WEBHOOK_URL,
        json={"content": f"🚀 **ResoFly System Online**\nAccess here: {url}"}
    )


import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_email(url):
    if "your.email" in EMAIL_RECEIVER or "app-password" in EMAIL_PASSWORD:
        return False
        
    print(f"Sending Email to {EMAIL_RECEIVER}...")
    try:
        msg = MIMEMultipart()
        msg['From'] = EMAIL_SENDER
        msg['To'] = EMAIL_RECEIVER
        msg['Subject'] = "ResoFly System Online - Access Link"

        body = f"""
        <html>
          <body>
            <h2>ResoFly is Online 🚀</h2>
            <p>The system has started successfully.</p>
            <p>Access your dashboard here:</p>
            <a href="{url}" style="font-size: 20px; font-weight: bold;">{url}</a>
            <p><small>(This link is generated by Cloudflare Quick Tunnel and changes on every reboot)</small></p>
          </body>
        </html>
        """
        msg.attach(MIMEText(body, 'html'))

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)
        text = msg.as_string()
        server.sendmail(EMAIL_SENDER, EMAIL_RECEIVER, text)
        server.quit()
        
        print("Email Sent Successfully!")
        return True
    except Exception as e:
        print(f"Email Failed: {e}")
        return False

if __name__ == "__main__":
    print("--- monitor_tunnel.py started ---")
    url = get_tunnel_url()
    
    if url:
        print(f"FOUND URL: {url}")
        
        # Try sending methods
        email_sent = send_email(url)
        sms_sent = send_sms(url)
        send_telegram(url)
        send_discord(url)
        
        if not (email_sent or sms_sent or TELEGRAM_BOT_TOKEN or DISCORD_WEBHOOK_URL):
            print("WARNING: No notification method configured! Please edit this file.")
    else:
        print("Timeout: Could not find URL in logs.")
