import time
import re
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# CONFIGURATION
# ------------------------------------------------------------------
# EMAIL SETTINGS (SMTP - Gmail/Outlook/etc)
EMAIL_SENDER = "resofly.alert@gmail.com"  # The email SENDING the alert
EMAIL_PASSWORD = "app-password-here"      # App Password (NOT your normal password)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

# File paths
LOG_FILE = os.path.expanduser("~/tunnel.log")
EMAIL_LIST_FILE = os.path.join(os.path.dirname(__file__), "email_list.txt")
# ------------------------------------------------------------------

def get_tunnel_url():
    """Reads the tunnel log and extracts the trycloudflare URL."""
    print(f"Checking for log file at: {LOG_FILE}")
    
    # Wait for file to exist
    retry_count = 0
    while not os.path.exists(LOG_FILE):
        if retry_count > 30: # 1 minute wait
             print("Log file never appeared.")
             return None
        time.sleep(2)
        retry_count += 1
    
    print("Log file found. Scanning for URL...")
    
    # Scan for URL
    start_time = time.time()
    url_pattern = re.compile(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com")
    
    while time.time() - start_time < 120: # timeout 2 mins
        try:
            with open(LOG_FILE, "r") as f:
                content = f.read()
                match = url_pattern.search(content)
                if match:
                    return match.group(0)
        except Exception as e:
            print(f"Error reading log: {e}")
            
        time.sleep(2)
        
    return None

def get_recipients():
    """Reads email addresses from email_list.txt"""
    recipients = []
    if os.path.exists(EMAIL_LIST_FILE):
        with open(EMAIL_LIST_FILE, 'r') as f:
            for line in f:
                line = line.strip()
                # Simple validation: looks for @ and no comments
                if line and not line.startswith('#') and '@' in line:
                    recipients.append(line)
    else:
        print(f"Warning: {EMAIL_LIST_FILE} not found!")
    
    return recipients

def send_email_to_all(url, recipients):
    if not recipients:
        print("No recipients found in email_list.txt")
        return False

    if "app-password" in EMAIL_PASSWORD:
        print("Error: EMAIL_PASSWORD not configured in monitor_tunnel.py")
        return False
        
    print(f"Connecting to SMTP server to email: {recipients}...")
    
    try:
        # Connect once
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_SENDER, EMAIL_PASSWORD)

        for recipient in recipients:
            try:
                print(f"Sending to {recipient}...")
                msg = MIMEMultipart()
                msg['From'] = EMAIL_SENDER
                msg['To'] = recipient
                msg['Subject'] = "ResoFly System Online 🚀"

                body = f"""
                <html>
                  <body>
                    <h2>ResoFly is Online</h2>
                    <p>The system has started successfully.</p>
                    <p>Access your dashboard here:</p>
                    <p><a href="{url}" style="background-color: #4CAF50; color: white; padding: 14px 20px; text-align: center; text-decoration: none; display: inline-block; border-radius: 4px; font-size: 16px;">Open Dashboard</a></p>
                    <p>Direct Link: {url}</p>
                    <hr>
                    <p><small>This link is generated by Cloudflare Quick Tunnel and changes on every reboot.</small></p>
                  </body>
                </html>
                """
                msg.attach(MIMEText(body, 'html'))
                
                server.sendmail(EMAIL_SENDER, recipient, msg.as_string())
            except Exception as e:
                print(f"Failed to send to {recipient}: {e}")

        server.quit()
        print("All emails processed.")
        return True
        
    except Exception as e:
        print(f"SMTP Connection Failed: {e}")
        return False

if __name__ == "__main__":
    print("--- monitor_tunnel.py started ---")
    
    # 1. Find the URL
    url = get_tunnel_url()
    
    if url:
        print(f"FOUND URL: {url}")
        
        # 2. Get Recipients
        recipients = get_recipients()
        print(f"Found {len(recipients)} recipients.")
        
        # 3. Send
        if recipients:
            send_email_to_all(url, recipients)
        else:
            print("Please add emails to 'email_list.txt'!")
    else:
        print("Timeout: Could not find URL in logs.")
